### ISSUE TITLE
Ability to pass additional headers in the htsget.get

### ISSUE THREAD

**Issue by aaclan-ebi** [ga4gh/htsget#40]
Hello! We're using the htsget.get method in our download client (i.e. [pyega3](https://pypi.org/project/pyega3/) )
Based on my understanding, htsget.get method does an initial request to get the URLs and other request info like parameters and headers to fetch the data slices from the htsget API. After getting these, it does all the succeeding requests behind the scenes to download all data slices.  

We would like to pass a custom header which contains a session id so that it will correlate all the log traces of an htsget request. 
However the htsget.get doesn't have this parameter available yet.

See related codes:

https://github.com/EGA-archive/ega-download-client/blob/master/pyega3/libs/data_file.py#L308-L316
https://github.com/ga4gh/htsget/blob/8be84325e18256e120d2b17a80f8f61adb0f17cc/htsget/io.py#L34-L80
https://github.com/ga4gh/htsget/blob/8be84325e18256e120d2b17a80f8f61adb0f17cc/htsget/protocol.py#L139-L140
https://github.com/ga4gh/htsget/blob/8be84325e18256e120d2b17a80f8f61adb0f17cc/htsget/io.py#L120-L126

**Comment by jeromekelleher** [comment]
HI @aaclan-ebi :wave: 

I think this should be a straightforward addition, and am happy to help get it in. Would you like to make a PR with the proposed updates?

**Comment by aaclan-ebi** [comment]
Hi @jeromekelleher, Thanks for your quick response! sure, let me get it ready soon. Many thanks!

**Comment by aaclan-ebi** [comment]
Hi @jeromekelleher , I've linked the PR to this issue, please review. Thanks!

**Comment by jeromekelleher** [comment]
Closed in #41

**Comment by aaclan-ebi** [comment]
I'll upgrade our version of htsget now. Thanks so much for your help on this @jeromekelleher !
